#Author: Balaji N
#Date: 28-06-2023
#Description: Demo the how repo workflow can access the org-level secrets and can do anything

name: "Access Org-Level Secret"
on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  contents: write

jobs:
  AccessOrgSecret:
    name: 'Org-Level secrets'
    runs-on: windows-latest
    env:
        OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_DEPLOY_API_KEY }}
        OCTOPUS_URL: ${{ secrets.OCTOPUS_HOST_URL }}
        OCTOPUS_HOST: ${{ secrets.OCTOPUS_HOST_URL }}
        OCTOPUS_SPACE: ${{ secrets.OCTOPUS_SPACE_NAME }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Octo CLI Install
      uses: OctopusDeploy/install-octopus-cli-action@v3
      with:
        version: '*'

    - name: list-octopusdeploy-accounts
      run: |
        octopus project list

    - name: Delete Octopus Project
      run: |
        $ErrorActionPreference = "Stop";

        # Define working variables
        $octopusURL = "${{ secrets.OCTOPUS_HOST_URL }}"
        $octopusAPIKey = "${{ secrets.OCTOPUS_DEPLOY_API_KEY }}"
        $header = @{ "X-Octopus-ApiKey" = $octopusAPIKey }
        $spaceName = "${{ secrets.OCTOPUS_SPACE_NAME }}"
        $projectName = "HelloWorld"

        # Get space
        $space = (Invoke-RestMethod -Method Get -Uri "$octopusURL/api/spaces/all" -Headers $header) | Where-Object {$_.Name -eq $spaceName}

        # Get project
        $project = (Invoke-RestMethod -Method Get -Uri "$octopusURL/api/$($space.Id)/projects/all" -Headers $header) | Where-Object {$_.Name -eq $projectName}

        # Delete project
        Invoke-RestMethod -Method Delete -Uri "$octopusURL/api/$($space.Id)/projects/$($project.Id)" -Headers $header
